// ActionScript file
private function funLoader():void
{
	_plaerLoader0 = new ImageLoader();
	_plaerLoader0.load("png/woman0.png");
	_plaerLoader0.addEventListener(Event.COMPLETE,manLoaded0);
	_plaerLoader1 = new ImageLoader();
	_plaerLoader1.load("png/woman1.png");
	_plaerLoader1.addEventListener(Event.COMPLETE,manLoaded1);
	_plaerLoader2 = new ImageLoader();
	_plaerLoader2.load("png/woman2.png");
	_plaerLoader2.addEventListener(Event.COMPLETE,manLoaded2);
	_plaerLoader3 = new ImageLoader();
	_plaerLoader3.load("png/woman3.png");
	_plaerLoader3.addEventListener(Event.COMPLETE,manLoaded3);
	_plaerLoader4 = new ImageLoader();
	_plaerLoader4.load("png/woman4.png");
	_plaerLoader4.addEventListener(Event.COMPLETE,manLoaded4);
	_plaerLoader5 = new ImageLoader();
	_plaerLoader5.load("png/woman5.png");
	_plaerLoader5.addEventListener(Event.COMPLETE,manLoaded5);
	_plaerLoader6 = new ImageLoader();
	_plaerLoader6.load("png/woman6.png");
	_plaerLoader6.addEventListener(Event.COMPLETE,manLoaded6);
	_plaerLoader7 = new ImageLoader();
	_plaerLoader7.load("png/woman7.png");
	_plaerLoader7.addEventListener(Event.COMPLETE,manLoaded7);
	_plaerLoader8 = new ImageLoader();
	_plaerLoader8.load("png/woman8.png");
	_plaerLoader8.addEventListener(Event.COMPLETE,manLoaded8);
	_plaerLoader9 = new ImageLoader();
	_plaerLoader9.load("png/woman9.png");
	_plaerLoader9.addEventListener(Event.COMPLETE,manLoaded9);
	_plaerLoader10 = new ImageLoader();
	_plaerLoader10.load("png/woman10.png");
	_plaerLoader10.addEventListener(Event.COMPLETE,manLoaded10);
	_plaerLoader11 = new ImageLoader();
	_plaerLoader11.load("png/woman11.png");
	_plaerLoader11.addEventListener(Event.COMPLETE,manLoaded11);
	_plaerLoader12 = new ImageLoader();
	_plaerLoader12.load("png/woman12.png");
	_plaerLoader12.addEventListener(Event.COMPLETE,manLoaded12);
	_plaerLoader13 = new ImageLoader();
	_plaerLoader13.load("png/woman13.png");
	_plaerLoader13.addEventListener(Event.COMPLETE,manLoaded13);
	_plaerLoader14 = new ImageLoader();
	_plaerLoader14.load("png/woman14.png");
	_plaerLoader14.addEventListener(Event.COMPLETE,manLoaded14);
	_plaerLoader15 = new ImageLoader();
	_plaerLoader15.load("png/woman15.png");
	_plaerLoader15.addEventListener(Event.COMPLETE,manLoaded15);
	_plaerLoader16 = new ImageLoader();
	_plaerLoader16.load("png/woman16.png");
	_plaerLoader16.addEventListener(Event.COMPLETE,manLoaded16);
	_plaerLoader17 = new ImageLoader();
	_plaerLoader17.load("png/woman17.png");
	_plaerLoader17.addEventListener(Event.COMPLETE,manLoaded17);
	_plaerLoader18 = new ImageLoader();
	_plaerLoader18.load("png/woman18.png");
	_plaerLoader18.addEventListener(Event.COMPLETE,manLoaded18);
	_plaerLoader19 = new ImageLoader();
	_plaerLoader19.load("png/woman19.png");
	_plaerLoader19.addEventListener(Event.COMPLETE,manLoaded19);
	_plaerLoader20 = new ImageLoader();
	_plaerLoader20.load("png/woman20.png");
	_plaerLoader20.addEventListener(Event.COMPLETE,manLoaded20);
	_plaerLoader21 = new ImageLoader();
	_plaerLoader21.load("png/woman21.png");
	_plaerLoader21.addEventListener(Event.COMPLETE,manLoaded21);
	_plaerLoader22 = new ImageLoader();
	_plaerLoader22.load("png/woman22.png");
	_plaerLoader22.addEventListener(Event.COMPLETE,manLoaded22);
	_plaerLoader23 = new ImageLoader();
	_plaerLoader23.load("png/woman23.png");
	_plaerLoader23.addEventListener(Event.COMPLETE,manLoaded23);
	_plaerLoader24 = new ImageLoader();
	_plaerLoader24.load("png/woman24.png");
	_plaerLoader24.addEventListener(Event.COMPLETE,manLoaded24);
	_plaerLoader25 = new ImageLoader();
	_plaerLoader25.load("png/woman25.png");
	_plaerLoader25.addEventListener(Event.COMPLETE,manLoaded25);
	_plaerLoader26 = new ImageLoader();
	_plaerLoader26.load("png/woman26.png");
	_plaerLoader26.addEventListener(Event.COMPLETE,manLoaded26);
	_plaerLoader27 = new ImageLoader();
	_plaerLoader27.load("png/woman27.png");
	_plaerLoader27.addEventListener(Event.COMPLETE,manLoaded27);
	_plaerLoader28 = new ImageLoader();
	_plaerLoader28.load("png/woman28.png");
	_plaerLoader28.addEventListener(Event.COMPLETE,manLoaded28);
	_plaerLoader29 = new ImageLoader();
	_plaerLoader29.load("png/woman29.png");
	_plaerLoader29.addEventListener(Event.COMPLETE,manLoaded29);
	_plaerLoader30 = new ImageLoader();
	_plaerLoader30.load("png/woman30.png");
	_plaerLoader30.addEventListener(Event.COMPLETE,manLoaded30);
	_plaerLoader31 = new ImageLoader();
	_plaerLoader31.load("png/woman31.png");
	_plaerLoader31.addEventListener(Event.COMPLETE,manLoaded31);
	_plaerLoader32 = new ImageLoader();
	_plaerLoader32.load("png/woman32.png");
	_plaerLoader32.addEventListener(Event.COMPLETE,manLoaded32);
	_plaerLoader33 = new ImageLoader();
	_plaerLoader33.load("png/woman33.png");
	_plaerLoader33.addEventListener(Event.COMPLETE,manLoaded33);
	_plaerLoader34 = new ImageLoader();
	_plaerLoader34.load("png/woman34.png");
	_plaerLoader34.addEventListener(Event.COMPLETE,manLoaded34);
	_plaerLoader35 = new ImageLoader();
	_plaerLoader35.load("png/woman35.png");
	_plaerLoader35.addEventListener(Event.COMPLETE,manLoaded35);
	_plaerLoader36 = new ImageLoader();
	_plaerLoader36.load("png/woman36.png");
	_plaerLoader36.addEventListener(Event.COMPLETE,manLoaded36);
	_plaerLoader37 = new ImageLoader();
	_plaerLoader37.load("png/woman37.png");
	_plaerLoader37.addEventListener(Event.COMPLETE,manLoaded37);
	_plaerLoader38 = new ImageLoader();
	_plaerLoader38.load("png/woman38.png");
	_plaerLoader38.addEventListener(Event.COMPLETE,manLoaded38);
	_plaerLoader39 = new ImageLoader();
	_plaerLoader39.load("png/woman39.png");
	_plaerLoader39.addEventListener(Event.COMPLETE,manLoaded39);
	_plaerLoader40 = new ImageLoader();
	_plaerLoader40.load("png/woman40.png");
	_plaerLoader40.addEventListener(Event.COMPLETE,manLoaded40);
	_plaerLoader41 = new ImageLoader();
	_plaerLoader41.load("png/woman41.png");
	_plaerLoader41.addEventListener(Event.COMPLETE,manLoaded41);
	_plaerLoader42 = new ImageLoader();
	_plaerLoader42.load("png/woman42.png");
	_plaerLoader42.addEventListener(Event.COMPLETE,manLoaded42);
	_plaerLoader43 = new ImageLoader();
	_plaerLoader43.load("png/woman43.png");
	_plaerLoader43.addEventListener(Event.COMPLETE,manLoaded43);
	_plaerLoader44 = new ImageLoader();
	_plaerLoader44.load("png/woman44.png");
	_plaerLoader44.addEventListener(Event.COMPLETE,manLoaded44);
	_plaerLoader45 = new ImageLoader();
	_plaerLoader45.load("png/woman45.png");
	_plaerLoader45.addEventListener(Event.COMPLETE,manLoaded45);
	_plaerLoader46 = new ImageLoader();
	_plaerLoader46.load("png/woman46.png");
	_plaerLoader46.addEventListener(Event.COMPLETE,manLoaded46);
	_plaerLoader47 = new ImageLoader();
	_plaerLoader47.load("png/woman47.png");
	_plaerLoader47.addEventListener(Event.COMPLETE,manLoaded47);
	_plaerLoader48 = new ImageLoader();
	_plaerLoader48.load("png/woman48.png");
	_plaerLoader48.addEventListener(Event.COMPLETE,manLoaded48);
	_plaerLoader49 = new ImageLoader();
	_plaerLoader49.load("png/woman49.png");
	_plaerLoader49.addEventListener(Event.COMPLETE,manLoaded49);
	_plaerLoader50 = new ImageLoader();
	_plaerLoader50.load("png/woman50.png");
	_plaerLoader50.addEventListener(Event.COMPLETE,manLoaded50);
	_plaerLoader51 = new ImageLoader();
	_plaerLoader51.load("png/woman51.png");
	_plaerLoader51.addEventListener(Event.COMPLETE,manLoaded51);
	_plaerLoader52 = new ImageLoader();
	_plaerLoader52.load("png/woman52.png");
	_plaerLoader52.addEventListener(Event.COMPLETE,manLoaded52);
	_plaerLoader53 = new ImageLoader();
	_plaerLoader53.load("png/woman53.png");
	_plaerLoader53.addEventListener(Event.COMPLETE,manLoaded53);
	_plaerLoader54 = new ImageLoader();
	_plaerLoader54.load("png/woman54.png");
	_plaerLoader54.addEventListener(Event.COMPLETE,manLoaded54);
	_plaerLoader55 = new ImageLoader();
	_plaerLoader55.load("png/woman55.png");
	_plaerLoader55.addEventListener(Event.COMPLETE,manLoaded55);
	_plaerLoader56 = new ImageLoader();
	_plaerLoader56.load("png/woman56.png");
	_plaerLoader56.addEventListener(Event.COMPLETE,manLoaded56);
	_plaerLoader57 = new ImageLoader();
	_plaerLoader57.load("png/woman57.png");
	_plaerLoader57.addEventListener(Event.COMPLETE,manLoaded57);
	_plaerLoader58 = new ImageLoader();
	_plaerLoader58.load("png/woman58.png");
	_plaerLoader58.addEventListener(Event.COMPLETE,manLoaded58);
	_plaerLoader59 = new ImageLoader();
	_plaerLoader59.load("png/woman59.png");
	_plaerLoader59.addEventListener(Event.COMPLETE,manLoaded59);
	_plaerLoader60 = new ImageLoader();
	_plaerLoader60.load("png/woman60.png");
	_plaerLoader60.addEventListener(Event.COMPLETE,manLoaded60);
	_plaerLoader61 = new ImageLoader();
	_plaerLoader61.load("png/woman61.png");
	_plaerLoader61.addEventListener(Event.COMPLETE,manLoaded61);
	_plaerLoader62 = new ImageLoader();
	_plaerLoader62.load("png/woman62.png");
	_plaerLoader62.addEventListener(Event.COMPLETE,manLoaded62);
	_plaerLoader63 = new ImageLoader();
	_plaerLoader63.load("png/woman63.png");
	_plaerLoader63.addEventListener(Event.COMPLETE,manLoaded63);
	_plaerLoader64 = new ImageLoader();
	_plaerLoader64.load("png/woman64.png");
	_plaerLoader64.addEventListener(Event.COMPLETE,manLoaded64);
	_plaerLoader65 = new ImageLoader();
	_plaerLoader65.load("png/woman65.png");
	_plaerLoader65.addEventListener(Event.COMPLETE,manLoaded65);
	_plaerLoader66 = new ImageLoader();
	_plaerLoader66.load("png/woman66.png");
	_plaerLoader66.addEventListener(Event.COMPLETE,manLoaded66);
	_plaerLoader67 = new ImageLoader();
	_plaerLoader67.load("png/woman67.png");
	_plaerLoader67.addEventListener(Event.COMPLETE,manLoaded67);
	_plaerLoader68 = new ImageLoader();
	_plaerLoader68.load("png/woman68.png");
	_plaerLoader68.addEventListener(Event.COMPLETE,manLoaded68);
	_plaerLoader69 = new ImageLoader();
	_plaerLoader69.load("png/woman69.png");
	_plaerLoader69.addEventListener(Event.COMPLETE,manLoaded69);
	_plaerLoader70 = new ImageLoader();
	_plaerLoader70.load("png/woman70.png");
	_plaerLoader70.addEventListener(Event.COMPLETE,manLoaded70);
	_plaerLoader71 = new ImageLoader();
	_plaerLoader71.load("png/woman71.png");
	_plaerLoader71.addEventListener(Event.COMPLETE,manLoaded71);
	_plaerLoader72 = new ImageLoader();
	_plaerLoader72.load("png/woman72.png");
	_plaerLoader72.addEventListener(Event.COMPLETE,manLoaded72);
	_plaerLoader73 = new ImageLoader();
	_plaerLoader73.load("png/woman73.png");
	_plaerLoader73.addEventListener(Event.COMPLETE,manLoaded73);
	_plaerLoader74 = new ImageLoader();
	_plaerLoader74.load("png/woman74.png");
	_plaerLoader74.addEventListener(Event.COMPLETE,manLoaded74);
	_plaerLoader75 = new ImageLoader();
	_plaerLoader75.load("png/woman75.png");
	_plaerLoader75.addEventListener(Event.COMPLETE,manLoaded75);
	_plaerLoader76 = new ImageLoader();
	_plaerLoader76.load("png/woman76.png");
	_plaerLoader76.addEventListener(Event.COMPLETE,manLoaded76);
	_plaerLoader77 = new ImageLoader();
	_plaerLoader77.load("png/woman77.png");
	_plaerLoader77.addEventListener(Event.COMPLETE,manLoaded77);
	_plaerLoader78 = new ImageLoader();
	_plaerLoader78.load("png/woman78.png");
	_plaerLoader78.addEventListener(Event.COMPLETE,manLoaded78);
	_plaerLoader79 = new ImageLoader();
	_plaerLoader79.load("png/woman79.png");
	_plaerLoader79.addEventListener(Event.COMPLETE,manLoaded79);
	_plaerLoader80 = new ImageLoader();
	_plaerLoader80.load("png/woman80.png");
	_plaerLoader80.addEventListener(Event.COMPLETE,manLoaded80);
	_plaerLoader81 = new ImageLoader();
	_plaerLoader81.load("png/woman81.png");
	_plaerLoader81.addEventListener(Event.COMPLETE,manLoaded81);
	_plaerLoader82 = new ImageLoader();
	_plaerLoader82.load("png/woman82.png");
	_plaerLoader82.addEventListener(Event.COMPLETE,manLoaded82);
	_plaerLoader83 = new ImageLoader();
	_plaerLoader83.load("png/woman83.png");
	_plaerLoader83.addEventListener(Event.COMPLETE,manLoaded83);
	_plaerLoader84 = new ImageLoader();
	_plaerLoader84.load("png/woman84.png");
	_plaerLoader84.addEventListener(Event.COMPLETE,manLoaded84);
	_plaerLoader85 = new ImageLoader();
	_plaerLoader85.load("png/woman85.png");
	_plaerLoader85.addEventListener(Event.COMPLETE,manLoaded85);
	_plaerLoader86 = new ImageLoader();
	_plaerLoader86.load("png/woman86.png");
	_plaerLoader86.addEventListener(Event.COMPLETE,manLoaded86);
	_plaerLoader87 = new ImageLoader();
	_plaerLoader87.load("png/woman87.png");
	_plaerLoader87.addEventListener(Event.COMPLETE,manLoaded87);
	_plaerLoader88 = new ImageLoader();
	_plaerLoader88.load("png/woman88.png");
	_plaerLoader88.addEventListener(Event.COMPLETE,manLoaded88);
	_plaerLoader89 = new ImageLoader();
	_plaerLoader89.load("png/woman89.png");
	_plaerLoader89.addEventListener(Event.COMPLETE,manLoaded89);
	_plaerLoader90 = new ImageLoader();
	_plaerLoader90.load("png/woman90.png");
	_plaerLoader90.addEventListener(Event.COMPLETE,manLoaded90);
	_plaerLoader91 = new ImageLoader();
	_plaerLoader91.load("png/woman91.png");
	_plaerLoader91.addEventListener(Event.COMPLETE,manLoaded91);
	_plaerLoader92 = new ImageLoader();
	_plaerLoader92.load("png/woman92.png");
	_plaerLoader92.addEventListener(Event.COMPLETE,manLoaded92);
	_plaerLoader93 = new ImageLoader();
	_plaerLoader93.load("png/woman93.png");
	_plaerLoader93.addEventListener(Event.COMPLETE,manLoaded93);
	_plaerLoader94 = new ImageLoader();
	_plaerLoader94.load("png/woman94.png");
	_plaerLoader94.addEventListener(Event.COMPLETE,manLoaded94);
	_plaerLoader95 = new ImageLoader();
	_plaerLoader95.load("png/woman95.png");
	_plaerLoader95.addEventListener(Event.COMPLETE,manLoaded95);
	_plaerLoader96 = new ImageLoader();
	_plaerLoader96.load("png/woman96.png");
	_plaerLoader96.addEventListener(Event.COMPLETE,manLoaded96);
	_plaerLoader97 = new ImageLoader();
	_plaerLoader97.load("png/woman97.png");
	_plaerLoader97.addEventListener(Event.COMPLETE,manLoaded97);
	_plaerLoader98 = new ImageLoader();
	_plaerLoader98.load("png/woman98.png");
	_plaerLoader98.addEventListener(Event.COMPLETE,manLoaded98);
	_plaerLoader99 = new ImageLoader();
	_plaerLoader99.load("png/woman99.png");
	_plaerLoader99.addEventListener(Event.COMPLETE,manLoaded99);
}